version: '3.1'

services:
  app:
    image: docker
    build: 
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    command: npm run start:dev

  db:
    image: mongo:latest
    ports:
      - "27017:27017"

    

